# Name of our workflow
name: Production deploy

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

# List of jobs
# A "job" is a set of steps that are executed on the same runner
jobs:
  build:
    # Operating system to run on
    runs-on: ubuntu-latest

    # List of steps that make up the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Node.js environment
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      # Install dependencies
      - name: Install dependencies
        run: yarn install

      # Run tests
      - name: Run tests
        run: yarn test

      # Build project
      - name: Build project
        run: yarn build

      # List build directory contents (for debugging)
      - name: List build directory contents (for debugging)
        run: ls -la ./build

  deploy:
    # Operating system to run on
    runs-on: ubuntu-latest

    # This job will only run if the `build` job is successful
    needs: build

    # List of steps that make up the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2

      # Deploy to Netlify
      - name: Netlify Deploy
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          # Auth token to use with netlify
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          # Your Netlify site id
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          # Directory where built files are stored
          build_directory: "./build"

      # Add check mark upon successful deployment
      - name: Add check mark
        run: echo "✅ Deployment successful"
